### ISSUE TITLE
Notification window misses url

### ISSUE THREAD

**Issue by morpheusthewhite** [Monti03/ChangesInWebPages#14]
When the monitored page finally changes the application opens a window which should probably show the url of the page which changed, but it is actually missing

![image](https://user-images.githubusercontent.com/36999173/73099823-9454a280-3eec-11ea-8add-a62654323091.png)

**Comment by Monti03** [comment]
solved in https://github.com/Monti03/ChangesInWebPages/commit/b6f2d21f0b380d6ef3b3a6b27a3776f8f9f959f1

**Comment by morpheusthewhite** [comment]
Nothing works

**Comment by Monti03** [comment]
I forgot a ")", now everything is working.

**Comment by morpheusthewhite** [comment]
We'll see it
