### ISSUE TITLE
requirements.txt needed

### ISSUE THREAD

**Issue by morpheusthewhite** [Monti03/ChangesInWebPages#2]
I suggest you to add the requirements.txt to install all needed python packages with

```
pip install -r requirements.txt
```

**Comment by Monti03** [comment]
partially solved in 528dd3327b7e4478c87ac7f45494c69be91eec5b

**Comment by morpheusthewhite** [comment]
I'm too lazy to run 4 different commands. Can you add an installation script?

**Comment by Monti03** [comment]
added build.sh in 1b181ac046ec11b64ef586093233229f4a748b35 -> now also lazy people can use it @morpheusthewhite
